title: <p align="center"> Kshitija Surange </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="mailto:kshtitija.iitkgp@gmail.com">Email</a> |
  <a href="https://www.linkedin.com/in/kshitija-surange/">LinkedIn</a> |
  <a href="https://github.com/kshitija-surange">GitHub</a>
  </p>
  
  <p align="justify">
  Hi, I am <b>Kshitija</b>! a Data Scientist with 3 years of experience. I am an alumnus of <a href="http://www.iitkgp.ac.in/">IIT Kharagpur</a> and currently working as Applied Data Scientist 2 in Mumbai.
  <br><br>
  Thank you for stopping by, you can check some of my projects here.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
